# apiVersion defines the Kubernetes API version.
# Secret uses the core v1 API.
apiVersion: v1

# kind tells Kubernetes we are creating a Secret.
kind: Secret

# metadata contains the name and namespace of the Secret.
metadata:

  # name of the Secret.
  # The Pod will refer to this name.
  name: app-secret

  # namespace where the Secret will be created.
  namespace: config-secret-demo

# type defines the Secret type.
# Opaque is the default type for custom key-value secrets.
type: Opaque

# stringData allows us to write plain text values in YAML.
# Kubernetes will automatically convert these values to base64 internally.
stringData:

  # Database username.
  DB_USERNAME: "admin"

  # Database password.
  DB_PASSWORD: "admin123"

  # This key will be mounted as a file later.
  credentials.txt: |
    username=admin
    password=admin123